[package]
name = "n-body"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bevy = "0.13.0"
bevy_egui = "0.27"
bevy_prototype_lyon = "0.11"
log = "0.4.22"
rand = "0.8.5"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
